//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLKS
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblSanPhamPhong
    {
        public int MaSPP { get; set; }
        public Nullable<int> MaPhieuDP { get; set; }
        public Nullable<int> MaSP { get; set; }
        public Nullable<int> SoLuong { get; set; }
        public Nullable<decimal> ThanhTien { get; set; }
        public Nullable<decimal> DonGia { get; set; }
    
        public virtual tblPhieuDatPhong tblPhieuDatPhong { get; set; }
        public virtual tblSanPham tblSanPham { get; set; }
    }
}
