//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLKS
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblTrangThietBiPhong
    {
        public int MaTTBP { get; set; }
        public Nullable<int> MaThietBi { get; set; }
        public Nullable<int> MaPhong { get; set; }
        public Nullable<int> SoLuong { get; set; }
        public Nullable<decimal> DonGia { get; set; }
        public Nullable<decimal> ThanhTien { get; set; }
    
        public virtual tblPhong tblPhong { get; set; }
        public virtual tblTrangThietBi tblTrangThietBi { get; set; }
    }
}
